### ISSUE TITLE
Wrong prediction for certain pictures of numbers

### ISSUE THREAD

**Issue by ft700** [ft700/mlExamples#1]
some numbers are predicted correctly, others are not. 

## Used files:
* run.sh : start the program

## Number "0"
manual created image as input data: 
![0_010](https://cloud.githubusercontent.com/assets/16255830/11766669/c1f2d1d6-a192-11e5-9e9d-2bde8667a30c.png)
modified image to meet mnist data requirements:   
![singlefileinputimage](https://cloud.githubusercontent.com/assets/16255830/11766684/09a72d1a-a193-11e5-8f8c-27225f8ff0f2.png)

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/0_010.png"`
Example output: `0,0,0,0,0,0,0,0,0,0,0,0,0,0,0`

## Number "1" ( German number format)
manual created image as input data: 
![1_010](https://cloud.githubusercontent.com/assets/16255830/11766705/0e31614c-a194-11e5-8c80-48c9518fd4d4.png)

modified image to meet mnist data requirements:   
![singlefileinputimage](https://cloud.githubusercontent.com/assets/16255830/11766710/3b14e4ea-a194-11e5-8aba-d713f2bb0356.png)

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/1_010.png"`
Example output: `9,9,9,9,9,9,9,9,9`

## Number "1" ( American number format)
manual created image as input data: 
![1_011](https://cloud.githubusercontent.com/assets/16255830/11809049/647cef8a-a324-11e5-8b29-1f91e1b1a530.png)
modified image to meet mnist data requirements:   
![singlefileinputimage](https://cloud.githubusercontent.com/assets/16255830/11809039/598a11d4-a324-11e5-86ee-91bcf2d8eba5.png)

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/1_011.png"`
Example output: `8,8,8,8,8,8,1,8`

## Number "2"
manual created image as input data: 
![2_010](https://cloud.githubusercontent.com/assets/16255830/11766724/a936bc78-a194-11e5-8a59-842d7b5a1368.png)
modified image to meet mnist data requirements:   
![singlefileinputimage](https://cloud.githubusercontent.com/assets/16255830/11766754/69e5793c-a195-11e5-8ca3-8c3422f91ee5.png)

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/2_010.png"`
Example output: `2,2,2,2,2,2,2,2,2,2,2,2`

## Number "3"
manual created image as input data: 
![3_010](https://cloud.githubusercontent.com/assets/16255830/11766734/c72948cc-a194-11e5-8aa8-28fb2e5fb722.png)
modified image to meet mnist data requirements: 
![singlefileinputimage](https://cloud.githubusercontent.com/assets/16255830/11766766/dc970e64-a195-11e5-8908-528a675a0f35.png)

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/3_010.png"`
Example output: `0,8,8,0,8,0,0`

 
## Number "3"
manual created image as input data: 
![3_001](https://cloud.githubusercontent.com/assets/16255830/11908311/3f959546-a5db-11e5-8124-7b572b214dcc.png)
modified image to meet mnist data requirements: 
![singlefileinputimage](https://cloud.githubusercontent.com/assets/16255830/11908313/489c9950-a5db-11e5-809a-dd8d1d21da58.png)

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/3_001.png"`
Example output: `3,3,3,3,3,3,3,3,3,3`

## Number "4"  ( German number format )
manual created image as input data: 
![4_010](https://cloud.githubusercontent.com/assets/16255830/11766735/d13e3f3e-a194-11e5-9c27-4c79ceab5059.png)
modified image to meet mnist data requirements:  
![singlefileinputimage](https://cloud.githubusercontent.com/assets/16255830/11766772/13161840-a196-11e5-9a62-ec5ee845caee.png)

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/4_010.png"`
Example output: `8,8,8,8,8,8,9`

## Number "4" ( American number format )
manual created image as input data: 
![4_011](https://cloud.githubusercontent.com/assets/16255830/11809132/08e25f4c-a325-11e5-9dd2-aacf0b1dc32b.png)
modified image to meet mnist data requirements:  
![singlefileinputimage](https://cloud.githubusercontent.com/assets/16255830/11809138/14ae35f8-a325-11e5-94de-9f63d8200c75.png)

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/4_011.png"`
Example output: `9,9,9,9,9,9,9,9`

## Number "4" ( American number format )
manual created image as input data: 
![4_001](https://cloud.githubusercontent.com/assets/16255830/11908344/a94064f8-a5db-11e5-9867-6365f0efe25d.png)
modified image to meet mnist data requirements:  
file:///home/marc/tensorflow/upload2git/mnist/numbers/handwritten/pro-img/basic/manualInput/singleFileInputImage.png

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/4_001.png"`
Example output: `4,4,4,4,4,4`

 
## Number "5"
manual created image as input data: 
![5_010](https://cloud.githubusercontent.com/assets/16255830/11766740/edf2c8d4-a194-11e5-96fb-b0cb4c652526.png)
modified image to meet mnist data requirements:   
![singlefileinputimage](https://cloud.githubusercontent.com/assets/16255830/11766779/548a8518-a196-11e5-880b-8b3cd19f0e48.png)

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/5_010.png"`
Example output: `5,5,5,5,5,5,5,5,5,5,5,5,5`

## Number "6"
manual created image as input data: 
![6_010](https://cloud.githubusercontent.com/assets/16255830/11766741/f6b9b0d6-a194-11e5-9650-5910dca15718.png)
modified image to meet mnist data requirements:   
![singlefileinputimage](https://cloud.githubusercontent.com/assets/16255830/11908368/e0dc36ee-a5db-11e5-860d-e9aba0e9188b.png)

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/6_010.png"`
Example output: `6,6,6,6,6,6,6,6`

## Number "7" ( German number format )
manual created image as input data: 
![7_010](https://cloud.githubusercontent.com/assets/16255830/11766743/fedfacc0-a194-11e5-9d13-a13daeee7a5b.png)
modified image to meet mnist data requirements:   
![singlefileinputimage](https://cloud.githubusercontent.com/assets/16255830/11766794/b8792c78-a196-11e5-820b-ffb4cdc62383.png)

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/7_010.png"`
Example output: `2,2,2,2,2,2,2,2,2,2,2,2,2`

## Number "7" ( American number format )
manual created image as input data: 
![7_011](https://cloud.githubusercontent.com/assets/16255830/11809352/a4a36c5e-a326-11e5-9f95-2171b90dff46.png)
modified image to meet mnist data requirements:   
![singlefileinputimage](https://cloud.githubusercontent.com/assets/16255830/11809236/a74fdf6a-a325-11e5-847d-6807cbb5ac55.png)

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/7_011.png"`
Example output: `1,1,1,1,1,1,1,1,1`

## Number "8"
manual created image as input data: 
![8_010](https://cloud.githubusercontent.com/assets/16255830/11766745/0e8f12fa-a195-11e5-9e0d-ab067f1011b6.png)
modified image to meet mnist data requirements:   
![singlefileinputimage](https://cloud.githubusercontent.com/assets/16255830/11908421/5aea4cb4-a5dc-11e5-9657-a32c956d945a.png)

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/8_010.png"`
Example output: `8,2,8,8,8,8,8,2,8`

## Number "9"  ( German number format )
manual created image as input data: 
![9_010](https://cloud.githubusercontent.com/assets/16255830/11766747/17757f9e-a195-11e5-933f-c157e73332bc.png)
modified image to meet mnist data requirements:   
![singlefileinputimage](https://cloud.githubusercontent.com/assets/16255830/11908443/8de4d5da-a5dc-11e5-97b2-bdedd072d63a.png)

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/9_010.png"`
Example output: `3,3,8,3,3,3,8,3,3`

## Number "9" ( American number format )
manual created image as input data: 
![9_011](https://cloud.githubusercontent.com/assets/16255830/11809295/2d6b6fe2-a326-11e5-8bc3-e4d653db6451.png)
modified image to meet mnist data requirements:   
![singlefileinputimage](https://cloud.githubusercontent.com/assets/16255830/11908481/cf45d010-a5dc-11e5-8264-faf27f8ab6ca.png)

Enabled in run.sh:    `python exec_01_normalizeImage.py --input "../numbers/handwritten/9_011.png"`
Example output: `3,3,3,3,3,3,3,3,3`

**Comment by Wikunia** [comment]
Thanks for reading my blog post ;)
You should know that MNIST is an American dataset therefore the "1" is only a straight line and the American seven looks like your 1. 
Is the example output the output for several different images or the output for the same image after running `run.sh` several times?

**Comment by ft700** [comment]
Thank you very much for your blog post, it is very well written and very useful for a machine learning greenhorn like me. Also thank you for the hint about the American number format of the MNIST data set, which explains of course why "1" was often recognized as "7" :)

The example output is the output for several different images. For each pass the appropriate line in run.sh was activated to link the image to the corresponding number documented above.

**Comment by Wikunia** [comment]
Okay, I have some work to do the next week but I'll check your images and will try to improve my code.

**Comment by ft700** [comment]
Used executable for testing : run02.sh

Always correct predictions if numbers "6", "4", "3" were written in blue front color on gray background.

Wrong predictions for following examples:
* "../numbers/handwritten/9_011.png"    :  3,3,3,3,3,3,3
* "../numbers/handwritten/9_010.png"    :  3,3,8,3,3,3,8
* "../numbers/handwritten/9_001.png"    :  3,3,3,3,3,3,3,3,3
* "../numbers/handwritten/7_011.png"    :  1,1,1,1,1
* "../numbers/handwritten/6_001.png"    :  2,2,2,2,2,2,8,2,8,2
* "../numbers/handwritten/4_010.png"    :  8,8,8,8,8,8,9
* "../numbers/handwritten/4_011.png"    :  9,9,9,9,9,9,9
* "../numbers/handwritten/1_011.png"    :  8,8,8,8,8,1,8

**Comment by ft700** [comment]
The issue has likely been partially caused by saving the flatten values in a file.

##### save the processed data of the images on disk
```
flatten = gray.flatten() / 255.0
output_file = open("../numbers/handwritten/pro-img/basic/manualInput/singleFileImage_data.data", 'wb')
flatten.tofile(output_file)
output_file.close()
```

##### load data from list:
```
input_file = open("../numbers/handwritten/pro-img/basic/manualInput/singleFileImage_data.data", 'r')
float_array = array('d')
float_array.fromstring(input_file.read())
input_file.close()
```

**Comment by ft700** [comment]
e.g. the 784-dim feature vector of number "1" (file: 1_011.png) looks like the following before it was flatten. It was classified as digit "8".

```
[
 [0 0 0 0 0 0 0 0 0 0 0 0   0   0   0   0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0   0   0   0   0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0   0   0   0   0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0   0   0   0   0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255   0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0   0   0   0   0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0   0   0   0   0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0   0   0   0   0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0   0   0   0   0 0 0 0 0 0 0 0 0 0 0 0 0]
 ]
```

**Comment by ft700** [comment]
Many thanks to Wikunia having solved the problem :)

**Comment by Wikunia** [comment]
did it solve every single case? I'm so sry for the bug

**Comment by ft700** [comment]
all test were successful, every single case has been solved :)
Many thanks for your excellent work  :+1:
